services:
  playground-fe:
    container_name: playground-fe
    image: boschvn/playground-fe:${IMAGE_TAG:-latest}
    ports:
      - "${APP_PORT:-8090}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
